import streamlit as st

if not st.session_state.get("logged_in", False):
    st.switch_page("app.py")
with st.sidebar:

    if st.button("🚪 Logout"):

        st.session_state.clear()

        st.switch_page("app.py")
import yagmail
import os

# ================= PAGE CONFIG ================= #

st.set_page_config(
    page_title="Email ATS Report",
    page_icon="📧",
    layout="wide"
)

# ================= CUSTOM CSS ================= #

page_style = """
<style>

.stApp {
    background: linear-gradient(rgba(0,0,0,0.82),
    rgba(0,0,0,0.82)),
    url("https://images.unsplash.com/photo-1516321318423-f06f85e504b3");
    background-size: cover;
    background-position: center;
    background-attachment: fixed;
}

section[data-testid="stSidebar"] {
    background-color: #111827;
}

.main-title {
    font-size: 58px;
    font-weight: bold;
    color: white;
}

.sub-title {
    color: #d1d5db;
    font-size: 22px;
    margin-bottom: 30px;
}

.card {
    background: rgba(255,255,255,0.08);
    padding: 30px;
    border-radius: 20px;
    border: 1px solid rgba(255,255,255,0.1);
    margin-top: 25px;
}

h1, h2, h3, p, label {
    color: white !important;
}

</style>
"""

st.markdown(page_style, unsafe_allow_html=True)

# ================= HEADER ================= #

st.markdown("""
<div class="main-title">📧 Email ATS Report</div>
<div class="sub-title">
Send Resume + ATS Report directly to recruiters
</div>
""", unsafe_allow_html=True)

# ================= CARD ================= #

st.markdown("""
<div class="card">

<h2>📨 Recruiter Email</h2>

<p>
SmartHire AI will send:
<br><br>
✅ Original Resume
<br>
✅ ATS Analysis Report PDF
</p>

</div>
""", unsafe_allow_html=True)

# ================= CHECK RESUME ================= #

if "resume_file" not in st.session_state:

    st.warning("⚠ Please upload resume first")

    st.stop()

# ================= OFFICIAL SMARTHIRE EMAIL ================= #

sender_email = "srilekhamallipudi4@gmail.com"

sender_password = "bgynrfhbndketuoe"

# ================= USER INPUT ================= #

receiver_email = st.text_input("Recruiter Email")

# ================= PDF FILE PATH ================= #

file_path = os.path.join(os.getcwd(), "ATS_Report.pdf")

# ================= GET RESUME FILE ================= #

resume_file = st.session_state["resume_file"]

# ================= SEND BUTTON ================= #

if st.button("📤 Send ATS Report"):

    if not receiver_email:

        st.warning("⚠ Please enter recruiter email")

    elif "@" not in receiver_email:

        st.warning("⚠ Invalid recruiter email")

    elif not os.path.exists(file_path):

        st.error("❌ ATS_Report.pdf not found. Generate report first.")

    else:

        try:

            # REMOVE SPACES
            sender_password = sender_password.replace(" ", "")

            # LOGIN SMTP
            yag = yagmail.SMTP(
                user=sender_email,
                password=sender_password
            )

            # SUBJECT
            subject = "SmartHire AI - Resume & ATS Report"

            # EMAIL BODY
            body = """
Hello Recruiter,

Please find the attached files generated by SmartHire AI.

Attachments Included:
• Original Candidate Resume
• ATS Resume Analysis Report

Report Includes:
• ATS Score
• Technical Skills Analysis
• Missing Skills Detection
• Resume Insights
• AI Recommendations
• Career Role Prediction

Regards,
SmartHire AI
"""

            # SEND EMAIL
            yag.send(
                to=receiver_email,
                subject=subject,
                contents=body,
                attachments=[
                    file_path,
                    resume_file
                ]
            )

            st.success(
                "✅ Resume and ATS Report Sent Successfully!"
            )

        except Exception as e:

            st.error("❌ Failed to Send Email")

            st.code(str(e))

# ================= INFO ================= #

st.markdown("""
<div class="card">

<h2>ℹ System Information</h2>

<p>
SmartHire AI automatically sends recruiter-ready
resume reports using secure Gmail SMTP integration.
</p>

</div>
""", unsafe_allow_html=True)